### ISSUE TITLE
Incorrect order in StageSwitch.h 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Syati#1]
SwitchIdInfo is defined after it is used in StageSwitchCtrl and the compiler doesn't like this

### CodeWarrior\mwcceppc.exe Compiler:
#      29:     SwitchIdInfo* mSW_B; // _4
#   Error:     ^^^^^^^^^^^^
#   (10140) undefined identifier 'SwitchIdInfo'

**Comment by shibbo** [comment]
fixed in 702233b
