### ISSUE TITLE
"CreatorUtil.h" was not found.

### ISSUE THREAD

**Issue by penguin117117** [shibbo/Syati#9]
"CreatorUtil.h" was not found.

CodeWarrior\mwcceppc.exe Compiler:
File: source\ExtendedActorFactory.cpp
----------------------------------------
4: #include "Util/CreatorUtil.h"
Error:          ^^^^^^^^^^^^^^^^^^^^
the file 'Util/CreatorUtil.h' cannot be opened

I had the previous file and was able to run it.
However, I thought that new users of this tool would not be able to use it, so I would like to report it.

**Comment by shibbo** [comment]
this issue was an old version of Syati, closing

**Comment by penguin117117** [comment]
We have confirmed that the latest version of Syati can create custom code for the Japanese version of SMG2.
Thank you very much for addressing this issue.
